version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    #    build: Uncomment this and comment image if you want to build it locally
    #      context: .
    #      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    #  environment:
    #    - CONFIG_PASSWORD=a
    #    - CONFIG_FILE_NAME=simple_pmm_example.py
    #    - SCRIPT_CONFIG=conf_simple_pmm_example.yaml

  # gateway:
  #  container_name: gateway
  #  image: hummingbot/gateway:latest
  #  ports:
  #    - "15888:15888"
  #    - "8080:8080"
  #  volumes:
  #    - "./gateway_files/conf:/home/gateway/conf"
  #    - "./gateway_files/logs:/home/gateway/logs"
  #    - "./gateway_files/db:/home/gateway/db"
  #    - "./certs:/home/gateway/certs"
  #  environment:
  #    - GATEWAY_PASSPHRASE=a

  broker:
    container_name: broker
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:5672:5672 # AMQP
      - 127.0.0.1:15672:15672 # Management
      - 127.0.0.1:1883:1883 # MQTT
      - 127.0.0.1:61613:61613 # STOMP
      - 127.0.0.1:15675:15675 # Web MQTT
      - 127.0.0.1:15674:15674 # Web STOMP
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/20-main.conf:/etc/rabbitmq/conf.d/20-main.conf:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5

  telegram_bot:
    container_name: telegram_bot
    image: hummingbot/telegram-bot
    restart: unless-stopped
    volumes:
      - ./telegram-bot/bots-info.json:/telegram-bot/bots-info.json
    environment:
      - TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
      - BROKER_HOST=broker
      - BROKER_PORT=1883
      - BROKER_USERNAME=admin
      - BROKER_PASSWORD=admin
      - BOTS_INFO_FILE=bots-info.json
      - BALANCE_THRESHOLD_IN_USD=${BALANCE_THRESHOLD_IN_USD}
      - TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}
      - MONITORING_INTERVAL_IN_MINS=${MONITORING_INTERVAL_IN_MINS}
